### ISSUE TITLE
It's too fast 😂

### ISSUE THREAD

**Issue by KalobTaulien** [thibaudcolas/-_-.css#1]
Hey. Great work on this css framework! 

I'm wondering if I'm able to slow it down a bit.. because it really is impossibly fast. I've had some complaints from website owners because they said their sites load super fast, but their users are expecting a delay like on every other website.

**Comment by thibaudcolas** [comment]
Hi Kalob,

Thanks for taking the time to report this. That’s a good point, and indeed that’s a known limitation of the approach we took in this framework. Perhaps this is something we should add opt-in support for, without changing the existing API? I’m thinking of something like:

```css
@keyframes \⏳ {
  from {
    opacity: 0;
  }

  to {
    opacity: 1;
  }
}

.\🐢{
  animation-name: \⏳;
  animation-duration: 2s;
}
```

You could then use this as `<body class="🦴 🐢">`. Or we could limit this to just 🦴, `<body class="🦴 🦴--🐢">`.

I think 🐢 is quite a good mood for this but also welcome suggestions for more appropriate moods.
